name: FrostedNameplates
version: ${version}
description: Allows customizing the text above players' heads
authors: [Pandier]

main: io.github.pandier.frostednameplates.internal.FrostedNameplatesPlugin
api-version: '1.20.6'

dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    MiniPlaceholders:
      load: BEFORE
      required: false

permissions:
  frostednameplates.command:
    description: Allows you to use the /frostednameplates command
    default: op
  frostednameplates.*:
    default: op
    children:
      frostednameplates.command: true
