name: FrostedNameplates
version: '${version}'
main: io.github.pandier.frostednameplates.FrostedNameplates
api-version: '1.21'
load: STARTUP
authors: [ Pandier ]
depend:
  - ProtocolLib
  - PlaceholderAPI
commands:
  frostednameplates:
    aliases: [fnp]
    permission: frostednameplates.command
permissions:
  frostednameplates.command:
    description: Allows you to use the /frostednameplates command
    default: op
  frostednameplates.*:
    default: op
    children:
      frostednameplates.command: true
