name: FrostedNametags
version: '${version}'
main: io.github.pandier.frostednametags.FrostedNametags
api-version: '1.21'
load: STARTUP
authors: [ Pandier ]
depend:
  - ProtocolLib
  - PlaceholderAPI
commands:
  frostednametags:
    aliases: [fnt]
    permission: frostednametags.command
permissions:
  frostednametags.command:
    description: Allows you to use the /frostednametags command
    default: op
  frostednametags.*:
    default: op
    children:
      frostednametags.command: true
