name: FrostedNameplates
version: ${version}
description: Allows customizing the text above players' heads
authors: [Pandier]

main: io.github.pandier.frostednameplates.internal.FrostedNameplatesPlugin
api-version: '1.19'

depend:
  - packetevents

softdepend:
  - PlaceholderAPI
  - MiniPlaceholders

commands:
  frostednameplates:
    aliases: [fnp]
    permission: frostednameplates.command

permissions:
  frostednameplates.command:
    description: Allows you to use the /frostednameplates command
    default: op
  frostednameplates.*:
    default: op
    children:
      frostednameplates.command: true
